import mongoose from "mongoose";

const TIME_PATTERN = /^([01]\d|2[0-3]):[0-5]\d$/;

const validateTimezone = {
  validator(value) {
    try {
      new Intl.DateTimeFormat("en-US", {
        timeZone: value || "Asia/Kolkata",
      }).format(new Date());
      return true;
    } catch {
      return false;
    }
  },
  message: "timezone is invalid",
};

const baseAgencyField = {
  type: mongoose.Schema.Types.ObjectId,
  ref: "Agency",
  required: true,
  index: true,
};

const userSettingsSchema = new mongoose.Schema(
  {
    agency_id: baseAgencyField,
    user_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    timezone: {
      type: String,
      default: "Asia/Kolkata",
      trim: true,
      validate: validateTimezone,
    },
    currency: {
      type: String,
      default: "INR",
      uppercase: true,
      trim: true,
    },
  },
  {
    timestamps: true,
    collection: "user_settings",
  }
);

userSettingsSchema.index({ agency_id: 1, user_id: 1 }, { unique: true });

const workspaceSettingsSchema = new mongoose.Schema(
  {
    agency_id: {
      ...baseAgencyField,
      unique: true,
    },
    logo_url: {
      type: String,
      trim: true,
      default: null,
    },
    default_sender_name: {
      type: String,
      trim: true,
      default: "Narrative Reports",
    },
    reply_to_email: {
      type: String,
      trim: true,
      lowercase: true,
      default: "",
    },
    from_email: {
      type: String,
      trim: true,
      lowercase: true,
      default: "reports@narrative.app",
    },
    custom_domain_status: {
      type: String,
      enum: ["coming_soon", "not_configured", "pending", "verified"],
      default: "coming_soon",
    },
    default_timezone: {
      type: String,
      default: "Asia/Kolkata",
      trim: true,
      validate: validateTimezone,
    },
    default_currency: {
      type: String,
      default: "INR",
      uppercase: true,
      trim: true,
    },
    report_footer_branding: {
      type: String,
      trim: true,
      default:
        "Generated by Narrative. This report is based on Meta Ads data available at send time.",
    },
    show_narrative_branding: {
      type: Boolean,
      default: true,
    },
    include_agency_name_in_footer: {
      type: Boolean,
      default: true,
    },
    include_generated_timestamp: {
      type: Boolean,
      default: true,
    },
    include_data_disclaimer: {
      type: Boolean,
      default: true,
    },
    report_email_tone: {
      type: String,
      enum: ["internal", "client_friendly"],
      default: "internal",
    },
  },
  {
    timestamps: true,
    collection: "workspace_settings",
  }
);

const reportDefaultSettingsSchema = new mongoose.Schema(
  {
    agency_id: {
      ...baseAgencyField,
      unique: true,
    },
    default_frequency: {
      type: String,
      enum: ["daily", "weekly", "monthly"],
      default: "daily",
    },
    daily_send_time: {
      type: String,
      default: "09:00",
      match: TIME_PATTERN,
    },
    weekly_day: {
      type: Number,
      min: 0,
      max: 6,
      default: 1,
    },
    weekly_time: {
      type: String,
      default: "09:00",
      match: TIME_PATTERN,
    },
    monthly_date: {
      type: Number,
      min: 1,
      max: 31,
      default: 1,
    },
    monthly_time: {
      type: String,
      default: "09:00",
      match: TIME_PATTERN,
    },
    timezone: {
      type: String,
      default: "Asia/Kolkata",
      trim: true,
      validate: validateTimezone,
    },
    comparison_window: {
      type: String,
      enum: [
        "previous_completed_day",
        "previous_completed_week",
        "previous_completed_month",
      ],
      default: "previous_completed_day",
    },
    recipients: {
      type: [String],
      default: [],
    },
    default_campaign_objective: {
      type: String,
      trim: true,
      default: "Leads",
    },
    default_kpi: {
      type: String,
      trim: true,
      default: "Cost per result",
    },
    sensitivity: {
      type: String,
      enum: ["low", "balanced", "high"],
      default: "balanced",
    },
  },
  {
    timestamps: true,
    collection: "report_default_settings",
  }
);

const notificationSettingsSchema = new mongoose.Schema(
  {
    agency_id: {
      ...baseAgencyField,
      unique: true,
    },
    email_report_delivery: {
      type: Boolean,
      default: true,
    },
    critical_alerts: {
      type: Boolean,
      default: true,
    },
    token_expiry_alerts: {
      type: Boolean,
      default: true,
    },
    failed_report_alerts: {
      type: Boolean,
      default: true,
    },
    weekly_summary: {
      type: Boolean,
      default: false,
    },
    manual_send_confirmation: {
      type: Boolean,
      default: true,
    },
    notify_before_meta_expiry: {
      type: Number,
      min: 1,
      max: 30,
      default: 7,
    },
  },
  {
    timestamps: true,
    collection: "notification_settings",
  }
);

export const UserSettings =
  mongoose.models.UserSettings ||
  mongoose.model("UserSettings", userSettingsSchema);

export const WorkspaceSettings =
  mongoose.models.WorkspaceSettings ||
  mongoose.model("WorkspaceSettings", workspaceSettingsSchema);

export const ReportDefaultSettings =
  mongoose.models.ReportDefaultSettings ||
  mongoose.model("ReportDefaultSettings", reportDefaultSettingsSchema);

export const NotificationSettings =
  mongoose.models.NotificationSettings ||
  mongoose.model("NotificationSettings", notificationSettingsSchema);
